openapi: "3.0.3"
info:
  title: API Facturacion
  description: Permite gestionar la facturación de Aveonline.
  version: "1.0.0"
servers:
  - url: http://localhost:{port}/{basePath}
    description: Servidor de desarrollo
    variables:
      port:
        default: "9092"
      basePath:
        default: v1
components:
  schemas:
    factura:
      type: object
      properties:
        id:
          type: integer
          format: int32
        fecha_crear:
          type: string
          format: date
        pago_total:
          type: number
          format: double
        promocion:
          $ref: "#/components/schemas/promocion"
        medicamentos:
          type: array
          items:
            $ref: "#/components/schemas/medicamento"
    factura-post:
      type: object
      properties:
        id:
          type: integer
          format: int32
        fecha_crear:
          type: string
          format: date
        pago_total:
          type: number
          format: double
        id_promocion:
          type: integer
          format: int32
        id_medicamentos:
          type: array
          items:
            type: integer
            format: int32
    medicamento:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        precio:
          type: number
          format: double
        ubicacion:
          type: string
    promocion:
      type: object
      properties:
        id:
          type: integer
          format: int32
        descripcion:
          type: string
        porcentaje:
          type: number
          format: double
        fecha_inicio:
          type: string
          format: date
        fecha_fin:
          type: string
          format: date
tags:
  - name: Facturas
    description: Acciones de facturas
  - name: Medicamentos
    description: Acciones de Medicamentos
  - name: Promociones
    description: Acciones de Promociones
paths:
  /factura:
    get:
      tags:
        - Facturas
      description: Retorna facturas
      parameters:
        - in: query
          name: fecha_inicio
          schema:
            type: string
            format: date
          required: false
          description: Incio del rango de fecha
        - in: query
          name: fecha_fin
          schema:
            type: string
            format: date
          required: false
          description: Fin del rango de fecha
      responses:
        "200":
          description: Lista de promociones.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/factura"

    post:
      tags:
        - Facturas
      description: Crea una nueva promocion
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/factura-post"
      responses:
        "200":
          description: promocion creada.
          content:
            application/json:
              schema:
                type: string
                example: promocion creado
        "400":
          description: error al crear la promocion.
          content:
            application/json:
              schema:
                type: string
                example: promocion no creada

  /factura/simular:
    get:
      tags:
        - Facturas
      description: Simular un factura
      parameters:
        - in: query
          name: id_medicamentos
          schema:
            type: array
            items:
              type: integer
              format: int32
          required: true
          description: Incio del rango de fecha
        - in: query
          name: fecha_compra
          schema:
            type: string
            format: date
          required: true
          description: Fin del rango de fecha
      responses:
        "200":
          description: valor simulado de la factura.
          content:
            application/json:
              schema:
                type: integer
                format: int32
  /medicamento:
    get:
      tags:
        - Medicamentos
      description: Retorna todos los medicamentos
      responses:
        "200":
          description: Lista de medicamentos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/medicamento"
    post:
      tags:
        - Medicamentos
      description: Crea nuevo medicamento
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/medicamento"
      responses:
        "200":
          description: crear medicamento.
          content:
            application/json:
              schema:
                type: string
                example: medicamento creado
        "400":
          description: error al crear el medicamento.
          content:
            application/json:
              schema:
                type: string
                example: medicamento no creado

  /promocion:
    get:
      tags:
        - Promociones
      description: Retorna todas las promociones
      responses:
        "200":
          description: Lista de promociones.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/promocion"
    post:
      tags:
        - Promociones
      description: Crea nueva promocion
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/promocion"
      responses:
        "200":
          description: crear promocion.
          content:
            application/json:
              schema:
                type: string
                example: promocion creado
        "400":
          description: error al crear promocion.
          content:
            application/json:
              schema:
                type: string
                example: promocion no creada
